### ISSUE TITLE
Add cyber visual monitor

### ISSUE THREAD

**Issue by amitaibu** [Gizra/pmi-shoov#1]
http://www.pmi.com/eng/pages/homepage.aspx

**Comment by mldk-tech** [comment]
![ct8uyopu8ae01rt300](https://cloud.githubusercontent.com/assets/5812423/12584047/51d2c8fa-c44e-11e5-9244-d393a7d7a484.jpg)

**Comment by mldk-tech** [comment]
Hi,
Access token is incorrect or no longer valid

**Comment by amitaibu** [comment]
please check now

**Comment by mldk-tech** [comment]
:+1:

**Comment by mldk-tech** [comment]
https://app.shoov.io/#/screenshots/13384

**Comment by mldk-tech** [comment]
http://gfycat.com/GrouchyBonyBergerpicard
